name: hgcal
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8   
  - pip=20.0.2
  - pytorch=1.4.0=py3.8_cuda10.0.130_cudnn7.6.3_0
  - torchvision=0.5.0=py38_cu100
  - cudatoolkit=10.0.130=0
  - pandas=1.0.1
  - uproot
  - scipy=1.4.1
  - tqdm=4.41
  - scikit-learn
  - pip:
        - mlflow
        - torch-cluster==1.4.5
        - torch-geometric==1.4.2
        - torch-scatter==1.4.0
        - torch-sparse==0.4.4
        - torch-spline-conv==1.1.1
        - git+https://github.com/LAL/trackml-library
