name: hgcal
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6   # or 2.7
  - pytorch=1.4.0
  - torchvision=0.5.0
  - cudatoolkit=9.0
  - pandas=0.25
  - matplotlib=3.1
  - jupyter
  - nbconvert==5.4.1
  - uproot
  - scipy=1.3
  - tqdm=4.41
