name: hgcal
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6   # or 2.7
  - pip=19.3.1=py36_0
  - pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0
  - torchvision=0.4.0=py36_cu100
  - cudatoolkit=10.0.130=0
  - pandas=0.25
  - matplotlib=3.1
  - jupyter
  - nbconvert==5.4.1
  - uproot
  - scipy=1.3
  - tqdm=4.41
  - scikit-learn
  - pip:
    - mlflow
    - torch-cluster==1.4.5
    - torch-geometric==1.3.2
    - torch-scatter==1.4.0
    - torch-sparse==0.4.3
    - torch-spline-conv==1.1.1
    - git+https://github.com/LAL/trackml-library

