# Input/output configuration
input_dir: /data/gnn_code/trackml-particle-identification/train_all
output_dir: /data/gnn_code/heptrkx-gnn-tracking/output
n_files: 9000

# Graph building configuration
selection:
    pt_min: 0.5 # GeV
    phi_slope_max: 0.0006
    z0_max: 150
    n_phi_sections: 4
    n_eta_sections: 2
    eta_range: [-5, 5]
